I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 504, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 514, in _execute_python_hide
    renpy.load("_reload-2")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 652, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 504, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 514, in _execute_python_hide
    renpy.load("_reload-2")
  File "renpy/loadsave.py", line 771, in load
    log.unfreeze(roots, label="_after_load")
  File "renpy/python.py", line 2200, in unfreeze
    self.rollback(0, force=True, label=label, greedy=greedy, on_load=True)
  File "renpy/python.py", line 2014, in rollback
    self.load_failed()
  File "renpy/python.py", line 1932, in load_failed
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Windows-10-10.0.19041
Ren'Py 7.4.9.2142
Testing 1.0
Tue Nov  9 18:38:27 2021
